name: Automatic Release
run-name: Release a new version of the icon pack on PR's merging

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, 'ci:')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout data from the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # Run Semantic-release-action with the included release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}